### ISSUE TITLE
[버그] 컬쳐랜드 카테고리 문제

### ISSUE THREAD

**Issue by leedonggyu1848** [yourtablecloth/TableClothCatalog#13]
**버그에 대한 설명**
컬쳐랜드 로고가 올바르게 다운로드 되지 않습니다.

**기대하는 동작**
https://yourtablecloth.github.io/TableClothCatalog/images/Service/CultureLand.png
위 링크 로고로 나타나는 것을 기대합니다.

**동영상 또는 스크린샷**
![BUG](https://user-images.githubusercontent.com/53461960/182008144-e8b4ed45-d6b1-4fb9-bcbe-d8bc24351c15.png)

**Comment by rkttu** [comment]
이 이슈는 known issue로 한 번 다운로드한 로고는 다시 다운로드하지 않도록 설계되어있어서 그렇습니다. TableCloth 리포지터리 쪽에 이슈를 새로 등록해주시면 감사하겠습니다.

**Comment by rkttu** [comment]
![image](https://user-images.githubusercontent.com/1297346/185738543-c5fd5059-a949-46d2-94ab-e1f564791e80.png)

문제 원인을 파악하여 수정했습니다.
