### ISSUE TITLE
동국대학교 정보시스템 (udrims) 추가 요청

### ISSUE THREAD

**Issue by incheon-kim** [yourtablecloth/TableClothCatalog#2]
[URL]
https://udrims.dongguk.edu/MiDongguk/install320U/MiPlatform_Updater321_20190129_1120.cab
https://udrims.dongguk.edu/MiDongguk/install320U/update_files_msi/MiPlatform_InstallBase320.msi
https://udrims.dongguk.edu/MiDongguk/install320U/update_files_msi/MiPlatform_InstallEngine320U.msi
https://udrims.dongguk.edu/MiDongguk/install320U/update_files_msi/MiPlatform_FixUACProblem320U.msi

[주의 사항]
MiPlatform_Updater321_20190129_1120.cab은 extract 했을 때 MiPlatform_Updater321.exe 와 MiUpdater321.inf 파일이 나옵니다.
cmd/powershell에서 cab 파일을 extract 하기 위해 사용한 커맨드는 "expand -F:* MiPlatform_Updater321_20190129_1120.cab {압축풀경로}" 입니다.

[설치 방법]
MiPlatform_Updater321.exe, MiPlatform_InstallBase320.msi, MiPlatform_InstallEngine320U.msi, MiPlatform_FixUACProblem320U.msi
모두 /passive 옵션을 주고 설치하면 정상 작동합니다.

"C:\Program Files (x86)\Internet Explorer\iexplore.exe" "http://udrims.dongguk.edu" 경로의 바로가기를 생성하는 것으로보아
IE11 에서 "http://udrims.dongguk.edu" 를 실행하면 동국대학교 정보시스템(udrim)가 실행되는 것 같습니다.

원래는 PR을 넣으려 했으나 원래 TableCloth 프로젝트에서도 cab 파일에 대한 대응이 필요한 것 같아 Issue로 등록하는 점 양해 부탁드리겠습니다..

**Comment by rkttu** [comment]
@incheon-kim 커스텀 설치 로직을 PowerShell 스크립트로 작성해서 테스트해보았으나, 의도했던 것과 다르게 웹 사이트가 제대로 실행되지 않았습니다.

https://github.com/yourtablecloth/TableClothCatalog/blob/main/docs/Catalog.xml#L1405

위의 PowerShell 코드를 테스트해주실 수 있을지 문의드립니다.

**Comment by rkttu** [comment]
@incheon-kim 0.5.4 버전을 출시하면서 카탈로그에 PowerShell 스크립트를 넣을 수 있게 개선했습니다. 다만 스크립트는 아직 검증되지 않은 상태입니다.

**Comment by rkttu** [comment]
이슈가 오랫동안 열려있어서 닫습니다. 추후 업데이트되는 내용이 있으면 새 이슈로 제보 부탁드립니다.
