### ISSUE TITLE
Hyper-V 사용안하는법 없을까요?

### ISSUE THREAD

**Issue by focskh** [yourtablecloth/TableClothCatalog#37]
앱플레이어 사용자들은 Hyper-V 를 꺼야 하기때문에
식탁보 사용을 위해  windows 가상화 사용시 Hyper-V 가 자동으로 켜지고 Hyper-V만 따로 끈다하더라도
식탁보 실행이 안되더라구요

혹시 Hyper-V 를 비활성화 하고 사용하는 방법은 없을까요

**Comment by sleeping-player** [comment]
> 앱플레이어 사용자들은 Hyper-V 를 꺼야 하기때문에 식탁보 사용을 위해 windows 가상화 사용시 Hyper-V 가 자동으로 켜지고 Hyper-V만 따로 끈다하더라도 식탁보 실행이 안되더라구요
> 
> 혹시 Hyper-V 를 비활성화 하고 사용하는 방법은 없을까요

식탁보 자체가 MS가 만든 윈도 샌드박스 기반으로 돌아가고
MS가 만들면 기본적으로 Hyper-V 기반입니다.
절대로 불가능합니다.
블루스택은 Hyper-V 버전 있으니 그거 쓰시는 방법 말고 없습니다.

**Comment by rkttu** [comment]
카탈로그에는 웹 사이트와 관련된 설정 변경, 웹 사이트 추가 요청에 관련된 이슈만 올리실 수 있습니다. 번거로우시겠지만, 기능 문의는 https://github.com/yourtablecloth/TableCloth 리포지터리의 이슈로 등록 부탁드립니다.
