### ISSUE TITLE
 SandBox 패키지설치 후 win11 Home 버전 이슈. Sandbox 설치된 Home에서는 안됨 

### ISSUE THREAD

**Issue by TeamOasis7** [yourtablecloth/TableClothCatalog#63]
win11 Home에 SandBox패키지를 설치하여 활성화 했습니다.

원도우 버전만으로 작동이 안되는 이유가 있을까요?

-https://forbes.tistory.com/716

**Comment by rkttu** [comment]
안녕하세요.

식탁보는 Windows 10 또는 Windows 11 Pro, Enterprise, Education 버전에서만 사용되는 것을 전제로 설계되었습니다. 다음의 이유로 인해 식탁보에서는 Home 버전의 Windows에서 동작을 검토해야 할 이유를 두고 있지 않는 점 양해 부탁드립니다.

- Microsoft는 Home 버전의 경우 최초 라이선스 판매 당시부터 Hyper-V나 Sandbox를 판매 단가에 넣어서 판매한 것이 아닙니다. (Pro 버전 대비 가격이 저렴한 이유가 있습니다.) 구매 조건에 일치하지 않는 점도 있고, Home 버전에서 단순히 패키지를 추가했다고 해서 Pro 버전처럼 Windows Sandbox가 정상 동작한다는 보장은 하기 어렵습니다.
- 식탁보 프로젝트가 Home 버전의 샌드박스 사용을 보장하지는 않습니다. 어디까지나 조건이 맞는 PC 환경을 갖춘 사용자에 한하여 제공하는 보조 유틸리티이므로, Windows 구성 요소에 관한 문의는 Microsoft에서만 정확히 답을 해주실 수 있을 것입니다.

아울러 이 리포지터리는 식탁보 애플리케이션의 문제점에 대한 질문을 받는 창구가 아닙니다. 식탁보의 기능 상 문제, 수정 사항이 있을 경우에는 https://github.com/yourtablecloth/TableCloth 리포지터리의 이슈로 등록해주시면 감사하겠습니다.
