### ISSUE TITLE
enabling winsxs 에서 상당시간을 멈춰 있습니다.

### ISSUE THREAD

**Issue by LanGsA0** [yourtablecloth/TableClothCatalog#76]
안녕하세요.
식탁보는 최신버전 사용중입니다.
윈도우 11(24H2)
enabling winsxs 에서 상당시간(십분가량) 을 멈춰 있습니다.

혹, 원인이나, 해결방법좀 있을까요?

**Comment by rkttu** [comment]
https://github.com/yourtablecloth/TableCloth/issues/227 이슈와 병합하여 살펴보도록 하겠습니다. 피드백 감사드립니다.
